### ISSUE TITLE
RPC over DDS server NotEnoughMemoryException

### ISSUE THREAD

**Issue by EloyRC** [eProsima/RPC#4]
RPC over DDS 1.03 running on Ubuntu 16.04 x64.

Running the example: 'rpcddsgen -example x64Linux2.6gcc4.4.5 hello.idl'

`hello.idl:
interface Hello
{
void hello();
};`

When running the server after starting the client I always get the exception:

`terminate called after throwing an instance of 'eprosima::fastcdr::exception::NotEnoughMemoryException'
  what():  Not enough memory in the buffer stream
Aborted (core dumped)`

I have not tried in other platforms.

**Comment by richiware** [comment]
I've tested with current master branch and this error stops happening. The generated code was updated to works with last release of Fast RTPS.
If you have any problem you could reopen this issue. Thanks @EloyRC
