### ISSUE TITLE
REST Over DDS/ FastRTPS

### ISSUE THREAD

**Issue by anandtp** [eProsima/RPC#6]
Is there an example of REST over FastRTPS over DDS, my systems on DDS and I want it to connect with AWS via REST . Is that possible.

**Comment by richiware** [comment]
RPC over REST is outdated. Currently RPC over FastRTPS is supported. Maybe our new product Integration Service 
(https://github.com/eProsima/Integration-Service) could be useful for you.

Sorry for the inconveniences.
↪ 2018-11-21 mié 15:02, anandtp <notifications@github.com>:
